### ISSUE TITLE
Downstream builds are failing...

### ISSUE THREAD

**Issue by misteroneill** [benjamn/ast-types#107]
Hard to tell exactly where, but this started happening immediately after 0.7.4 was released:

```
AssertionError: did not recognize object of type "ModuleSpecifier"
    at Object.getFieldNames (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:595:16)
    at visitChildren (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:203:32)
    at Visitor.PVp.visitWithoutReset (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at NodePath.each (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    at visitChildren (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:199:14)
    at Visitor.PVp.visitWithoutReset (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/home/travis/build/REDACTED/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
```

The entire stack trace appears to be within ast-types. I'm having trouble tracing down the exact source, but this is the only lead I have so far and it doesn't seem coincidental. Wanted to put it on your radar and see if you had any insight because our team is trying to ship an important application this weekend.

**Comment by misteroneill** [comment]
Seems to happen with 0.7.3, too. Manually downgrading to 0.7.2 seems to fix it.

**Comment by benjamn** [comment]
Sorry about this! I think it was #105. Fix coming momentarily.

**Comment by misteroneill** [comment]
@benjamn I wish I could tell you how much I (and many others) appreciate this!
