### ISSUE TITLE
`npm test` fails on nodeJS 10.x: TypeError [ERR_AMBIGUOUS_ARGUMENT]: The "error/message" argument is ambiguous

### ISSUE THREAD

**Issue by GerHobbelt** [benjamn/ast-types#270]
This was reported when running `npm test`:

```
  1) types.eachField
       should complain about invalid types:
     TypeError [ERR_AMBIGUOUS_ARGUMENT]: The "error/message" argument is ambiguous. The error message "did not recognize object of type "asdf"" is identical to the message.
      at expectsError (assert.js:487:15)
      at Function.throws (assert.js:548:3)
      at Context.<anonymous> (lib\js\ast-types\test\ecmascript.js:406:12)
      at callFn (lib\js\ast-types\node_modules\mocha\lib\runnable.js:383:21)
      ...
```

Turns out node v10 has some additional assert sanity checks: if the thrown error message text equals the assert function call's descriptive message text argument, this is the error reported.

Fix is coming up...

**Comment by bnjmnt4n** [comment]
This issue, along with #271, can be closed since a fix was already implemented in 41128696e276ecc8251f0de18b7fe0668152100f.
