### ISSUE TITLE
t.exportSpecifier doesn't work in ^0.14.0

### ISSUE THREAD

**Issue by jedwards1211** [benjamn/ast-types#425]
I don't fully understand what's supposed to happen when a node type is defined in two places (esprima and es6) but it seems to be causing problems for `exportSpecifier`:

```
> var t = require('ast-types').builders
undefined
> t.exportSpecifier()
Uncaught:
Error: no value or default function given for field "exported" of ExportSpecifier("id": Identifier | null, "name": Identifier | null)
    at addParam (/Users/andy/temp/node_modules/ast-types/lib/types.js:443:27)
    at /Users/andy/temp/node_modules/ast-types/lib/types.js:477:21
    at Array.forEach (<anonymous>)
    at Object.builder [as exportSpecifier] (/Users/andy/temp/node_modules/ast-types/lib/types.js:475:46)
> t.exportSpecifier(t.identifier('foo'), t.identifier('bar'))
Uncaught:
Error: no value or default function given for field "exported" of ExportSpecifier("id": Identifier | null, "name": Identifier | null)
    at addParam (/Users/andy/temp/node_modules/ast-types/lib/types.js:443:27)
    at /Users/andy/temp/node_modules/ast-types/lib/types.js:477:21
    at Array.forEach (<anonymous>)
    at Object.builder [as exportSpecifier] (/Users/andy/temp/node_modules/ast-types/lib/types.js:475:46)
```

I noticed that field names `id` and `name` come from the esprima defs, whereas the field name `exported` comes from the es6 defs.

**Comment by jedwards1211** [comment]
Oh I see now what the problem is: in 0.13.4, [`ExportSpecifier` was declared in the babel defs](https://github.com/benjamn/ast-types/commit/ff020a8b5e56028234267d9870b25b208541e9c6#diff-13a781ef7bdda9df1128815d874371daL85) which [come after esprima](https://github.com/benjamn/ast-types/blob/master/main.ts#L56).

That declaration of [`ExportSpecifier` was moved to the es6 defs in 0.14.0](https://github.com/benjamn/ast-types/commit/ff020a8b5e56028234267d9870b25b208541e9c6#diff-aa48f38a3216267094e34a4ac32826b5R258), which [comes before esprima](https://github.com/benjamn/ast-types/blob/master/main.ts#L47)

**Comment by sibelius** [comment]
I've got this problem as well

what is the best way to fix it? downgrade for now?

is there a changelog for this?

**Comment by jedwards1211** [comment]
I downgraded for the time being.

If you look at https://github.com/benjamn/ast-types/blob/master/main.ts, you can see how you could copy this code into your own bootstrapper and tweak the available defs/ordering -- assuming you're not using a tool like `jscodeshift` which imports the `main` module.

**Comment by sibelius** [comment]
where is a good place to add these regressions tests?

**Comment by fersilva16** [comment]
You can use the `.from` function as a workaround for it

```ts
j.exportSpecifier.from({
  exported: j.identifier('something'),
  local: j.identifier('something'), // Optional
})
```

**Comment by benjamn** [comment]
Still reproducible on current `master`: `builders.exportSpecifier(local, exported)` throws "no value or default function given for field "exported" of ExportSpecifier("id": Identifier | null, "name": Identifier | null)". The cause is that `src/def/esprima.ts` redefines `ExportSpecifier` with `.build("id", "name")` after `src/def/es6.ts` defined it with `.build("local", "exported")`, and the later `build()` call replaces the parameter list. `builders.exportSpecifier.from({ local, exported })` works as a workaround. #378 proposed unifying the esprima and es6 specifier definitions now that esprima follows ESTree, which is the right fix; keeping this open until that lands.
