### ISSUE TITLE
Can we add "TSSatisfiesExpression" to src/def/typescript.ts

### ISSUE THREAD

**Issue by skvale** [benjamn/ast-types#935]
Without TSSatisfiesExpression

```
/Users/me/project/node_modules/ast-types/lib/types.js:664
            throw new Error("did not recognize object of type " +
            ^

Error: did not recognize object of type "TSSatisfiesExpression"
    at Object.getFieldNames (/Users/me/project/node_modules/ast-types/lib/types.js:664:19)
    at visitChildren (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:184:36)
    at PVp.visitWithoutReset (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:166:20)
    at visitChildren (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:203:25)
    at PVp.visitWithoutReset (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:166:20)
    at NodePath.each (/Users/me/project/node_modules/ast-types/lib/path.js:87:26)
    at visitChildren (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:178:18)
    at PVp.visitWithoutReset (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:166:20)
    at visitChildren (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:203:25)
    at PVp.visitWithoutReset (/Users/me/project/node_modules/ast-types/lib/path-visitor.js:166:20)

Node.js v18.12.1
```

"typescript": "^4.9.5",

TS docs: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator

<details>
<summary>Example syntax</summary>

```ts
type Colors = "red" | "green" | "blue";
type RGB = [red: number, green: number, blue: number];
const palette = {
    red: [255, 0, 0],
    green: "#00ff00",
    bleu: [0, 0, 255]
} satisfies Record<Colors, string | RGB>;
```

</details>

**Comment by JamesNimlos** [comment]
I believe this can be closed. It was implemented in https://github.com/benjamn/ast-types/pull/886 and others [mentioned fixing this issue](https://github.com/vue-styleguidist/vue-styleguidist/pull/1537/files#diff-8355a180c557ed3b2ab5cec6dbfca912fbfc9bce3f5e4591bdd978f9b3e1a9f6R43) by upgrading to `ast-types@0.16.1` or higher.

**Comment by benjamn** [comment]
Thanks for filing this, and sorry it sat unanswered for so long. The report was correct, and it turned out to already be fixed in code without being fixed for most users.

`TSSatisfiesExpression` was added in 4a014e0 (December 2022) and is in every release from v0.16.0 onward, but those releases were published under the `next` dist-tag, so a plain `npm install ast-types` still resolves to 0.14.2 and doesn't have it. Until `latest` is moved forward, `npm install ast-types@next` (or `ast-types@^0.16.1`, which is what recast depends on) gets you the definition. Closing since the def itself has existed for some time; the dist-tag situation is being sorted out separately.
